<?php

########################################################################
# Extension Manager/Repository config file for ext: "orthodox"
#
# Auto generated by Extension Builder 2012-10-19
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Orthodox',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Dmitri Pisarev',
	'author_email' => 'dimaip@gmail.com',
	'author_company' => 'PSMB',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.5',
			'fluid' => '1.5',
			'typo3' => '4.7',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>